### PR TITLE
Update to the iPhone version and new version of the original TouchOSC

### PR DESCRIPTION
**Pull request by Raiden38**
Hi!
I update my original iPhone version that is on the GitHub in User-Submitted.

I have also upgraded the original TouchOsc with new playback tab, changed the attributes page with 14 attributes (mainly for Multi-Parameter devices) and a few bug fixes. I renamed it V2, as I don't know if you want to keep it like this, or change the original one, or put it in user submitted. Let me know. 

Steven

### CODE REVIEW

**Comment by hinrichsenhans** [comment]
Are there things in v1 that aren't present in v2? If v2 is just a version with more features, I'd say just replace the file directly. The beauty of git is that we can always go backwards to the original version if we had to.

**Comment by Raiden38** [comment]
All the tabs have improvements (plus one complete new tab), but the only thing that I have removed is in the attributes tab. I have removed the Min Home and Max buttons below the encoders, and I have removed the color selection on the bottom right. I have put 14 encoders in total, so you can imagine that I needed some space to do it... I have replaced the preset button with a Home button, that works for the whole device.

I can check if there would be a way to add back the home for each encoder, but i don't know where I could put the colors....

**Comment by Raiden38** [comment]
Please do not branch, I will upload a new version with the home available for each encoder... I will test it out tomorrow with a show I have. Thanks! 

PS: I am not sure how to cancel this pull request...

**Comment by hinrichsenhans** [comment]
I can go ahead and close the PR. No worries!

**Pull request closed without merging**
